"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var router = express_1.default.Router();
var AdminController_1 = require("../Controller/AdminController");
router.get("/fetch-user-admin", AdminController_1.default.fetch_User_Admin);
router.post("/edit-user", AdminController_1.default.EditUserName);
router.post("/add-user-admin", AdminController_1.default.Add_New_User);
router.post("/delete-user-admin", AdminController_1.default.Delete_User);
exports.default = router;
